### ISSUE TITLE
discord rpc problem

### ISSUE THREAD

**Issue by DTCgamerTV** [Cheese-Curd/PlantsVSZombiesHaxe#3]
Discord rpc isnt working and its not allowing the program to compile it.

![image](https://user-images.githubusercontent.com/77363676/160958707-e81c6f2e-48a0-434d-b34c-91c4e90c78c0.png)

**Comment by Cheese-Curd** [comment]
https://github.com/Aidan63/linc_discord-rpc
Try downloading this

**Comment by Cheese-Curd** [comment]
no response so I'm assuming that fixed it
